# Analysis of data from McDonalds menu
---
## Questions to be answered:
1. How many calories does the average McDonald's value meal contain? 
2. How much do beverages, like soda or coffee, contribute to the overall caloric intake? 
3. Does ordered grilled chicken instead of crispy increase a sandwich's nutritional value? 
4. What about ordering egg whites instead of whole eggs? 
5. What is the least number of items could you order from the menu to meet one day's nutritional requirements?

# Importing data and preliminary checks

In [2]:
# Standard imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as pplot
%matplotlib inline
import seaborn as ss

In [71]:
# Import menu with pandas
menu = pd.read_csv('menu.csv')

In [5]:
# Check the dataset using head().
# '-5' is used to see the first 5 and the last 5 entries.
menu.head(-5)

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Smoothies & Shakes,Shamrock Shake (Medium),16 fl oz cup,660,170,19.0,29,12.0,61,1.0,...,109,36,0,0,93,14,25,0,50,0
251,Smoothies & Shakes,Shamrock Shake (Large),22 fl oz cup,820,210,23.0,35,15.0,73,1.0,...,135,45,0,0,115,18,30,0,60,0
252,Smoothies & Shakes,McFlurry with M&M’s Candies (Small),10.9 oz (310 g),650,210,23.0,35,14.0,72,0.5,...,96,32,1,6,89,13,15,0,45,8
253,Smoothies & Shakes,McFlurry with M&M’s Candies (Medium),16.2 oz (460 g),930,290,33.0,50,20.0,102,1.0,...,139,46,2,7,128,20,25,0,70,10
254,Smoothies & Shakes,McFlurry with M&M’s Candies (Snack),7.3 oz (207 g),430,140,15.0,24,10.0,48,0.0,...,64,21,1,4,59,9,10,0,30,4

In [6]:
# Check out the data using '.describe()' to see a summary of all numerical data
menu.describe()

,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,Cholesterol,Cholesterol (% Daily Value),Sodium,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
count,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,...,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000
mean,368.269231,127.096154,14.165385,21.815385,6.007692,29.965385,0.203846,54.942308,18.392308,495.750000,...,47.346154,15.780769,1.630769,6.530769,29.423077,13.338462,13.426923,8.534615,20.973077,7.734615
std,240.269886,127.875914,14.205998,21.885199,5.321873,26.639209,0.429133,87.269257,29.091653,577.026323,...,28.252232,9.419544,1.567717,6.307057,28.679797,11.426146,24.366381,26.345542,17.019953,8.723263
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,210.000000,20.000000,2.375000,3.750000,1.000000,4.750000,0.000000,5.000000,2.000000,107.500000,...,30.000000,10.000000,0.000000,0.000000,5.750000,4.000000,2.000000,0.000000,6.000000,0.000000
50%,340.000000,100.000000,11.000000,17.000000,5.000000,24.000000,0.000000,35.000000,11.000000,190.000000,...,44.000000,15.000000,1.000000,5.000000,17.500000,12.000000,8.000000,0.000000,20.000000,4.000000
75%,500.000000,200.000000,22.250000,35.000000,10.000000,48.000000,0.000000,65.000000,21.250000,865.000000,...,60.000000,20.000000,3.000000,10.000000,48.000000,19.000000,15.000000,4.000000,30.000000,15.000000
max,1880.000000,1060.000000,118.000000,182.000000,20.000000,102.000000,2.500000,575.000000,192.000000,3600.000000,...,141.000000,47.000000,7.000000,28.000000,128.000000,87.000000,170.000000,240.000000,70.000000,40.000000

In [13]:
# Check and make sure that we don't have any null values before proceeding with the data analysis
print(menu.isnull().sum())

Category                         0
Item                             0
Serving Size                     0
Calories                         0
Calories from Fat                0
Total Fat                        0
Total Fat (% Daily Value)        0
Saturated Fat                    0
Saturated Fat (% Daily Value)    0
Trans Fat                        0
Cholesterol                      0
Cholesterol (% Daily Value)      0
Sodium                           0
Sodium (% Daily Value)           0
Carbohydrates                    0
Carbohydrates (% Daily Value)    0
Dietary Fiber                    0
Dietary Fiber (% Daily Value)    0
Sugars                           0
Protein                          0
Vitamin A (% Daily Value)        0
Vitamin C (% Daily Value)        0
Calcium (% Daily Value)          0
Iron (% Daily Value)             0
dtype: int64

In [8]:
# Print the types to see if anything should be changed.
print(menu.dtypes)

Category                          object
Item                              object
Serving Size                      object
Calories                           int64
Calories from Fat                  int64
Total Fat                        float64
Total Fat (% Daily Value)          int64
Saturated Fat                    float64
Saturated Fat (% Daily Value)      int64
Trans Fat                        float64
Cholesterol                        int64
Cholesterol (% Daily Value)        int64
Sodium                             int64
Sodium (% Daily Value)             int64
Carbohydrates                      int64
Carbohydrates (% Daily Value)      int64
Dietary Fiber                      int64
Dietary Fiber (% Daily Value)      int64
Sugars                             int64
Protein                            int64
Vitamin A (% Daily Value)          int64
Vitamin C (% Daily Value)          int64
Calcium (% Daily Value)            int64
Iron (% Daily Value)               int64
dtype: object

# Question 1
1. How many calories does the average McDonald's value meal contain? 
---
A value meal from McDonalds is any one of their main items (hamburgers, fish, chicken), with a medium french fry or salad and a drink.

In [12]:
# Check the categories to see where the information we want would be.
# Could just print them, but I saved the list to a variable just in case we need them later.
categories = menu['Category'].unique()
print(categories)

['Breakfast' 'Beef & Pork' 'Chicken & Fish' 'Salads' 'Snacks & Sides'
 'Desserts' 'Beverages' 'Coffee & Tea' 'Smoothies & Shakes']

In [15]:
# Create a new df with only the categories that matter for us here. In this case the category, item name, and calory number.
menu_calories = menu[['Category', 'Item', 'Calories']]
menu_calories.head(-5)

               Category                                  Item  Calories
0             Breakfast                          Egg McMuffin       300
1             Breakfast                     Egg White Delight       250
2             Breakfast                      Sausage McMuffin       370
3             Breakfast             Sausage McMuffin with Egg       450
4             Breakfast      Sausage McMuffin with Egg Whites       400
..                  ...                                   ...       ...
250  Smoothies & Shakes               Shamrock Shake (Medium)       660
251  Smoothies & Shakes                Shamrock Shake (Large)       820
252  Smoothies & Shakes   McFlurry with M&M’s Candies (Small)       650
253  Smoothies & Shakes  McFlurry with M&M’s Candies (Medium)       930
254  Smoothies & Shakes   McFlurry with M&M’s Candies (Snack)       430

[255 rows x 3 columns]

In [46]:
# Pull out the snacks and sides. For this however, we only want Medium French Fries. we'll pull that out individually later.
Snacks_and_sides = menu_calories[menu_calories['Category'] == 'Snacks & Sides'].copy()
Snacks_and_sides.head()

          Category                                        Item  Calories
90  Snacks & Sides    Chipotle BBQ Snack Wrap (Crispy Chicken)       340
91  Snacks & Sides   Chipotle BBQ Snack Wrap (Grilled Chicken)       260
92  Snacks & Sides   Honey Mustard Snack Wrap (Crispy Chicken)       330
93  Snacks & Sides  Honey Mustard Snack Wrap (Grilled Chicken)       250
94  Snacks & Sides           Ranch Snack Wrap (Crispy Chicken)       360

In [47]:
# Pull out the sandwiches (though this does include chicken nuggets too) into their own dataframe.
sandwiches = menu_calories[(menu_calories['Category'].isin(['Beef & Pork', 'Chicken & Fish']))].copy()
sandwiches.head()

       Category                                       Item  Calories
42  Beef & Pork                                    Big Mac       530
43  Beef & Pork                Quarter Pounder with Cheese       520
44  Beef & Pork        Quarter Pounder with Bacon & Cheese       600
45  Beef & Pork  Quarter Pounder with Bacon Habanero Ranch       610
46  Beef & Pork                     Quarter Pounder Deluxe       540

In [48]:
# Pull out the salads into their own data frame.
salads = Snacks_and_sides = menu_calories[menu_calories['Category'] == 'Salads'].copy()
salads

   Category                                            Item  Calories
84   Salads     Premium Bacon Ranch Salad (without Chicken)       140
85   Salads   Premium Bacon Ranch Salad with Crispy Chicken       380
86   Salads  Premium Bacon Ranch Salad with Grilled Chicken       220
87   Salads       Premium Southwest Salad (without Chicken)       140
88   Salads     Premium Southwest Salad with Crispy Chicken       450
89   Salads    Premium Southwest Salad with Grilled Chicken       290

In [44]:
# Pull out the drinks into their own dataframe.
drinks = menu_calories[menu_calories['Category'] == 'Beverages'].copy()

In [82]:
# Use merge to create the cartesian product of the different menu items
# to calculate the total caloric value of each kind of meal.
from pandas import merge

# Add a 'key' column and set it to 1 so that we can merge dataframes together.
drinks['key'] = 1
salads['key'] = 1
sandwiches['key'] = 1

# Create cartesian product of drinks and salads.
drink_salad_cartesian = merge(drinks, salads, on='key')

# Create cartesian product of drinks, salads, and sandwiches.
sandwich_drink_salad = merge(drink_salad_cartesian, sandwiches, on='key')

# Check to make sure it worked.
sandwich_drink_salad.head()

,Category_x,Item_x,Calories_x,key,Category_y,Item_y,Calories_y,Category,Item,Calories
0,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Big Mac,530
1,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Cheese,520
2,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon & Cheese,600
3,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,610
4,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder Deluxe,540

In [97]:
# Rename the columns so that they make more sense.
sandwich_drink_salad.rename(columns = {'Calories_x':'Beverage_Calories',
                                      'Calories_y': 'Salad_Calories',
                                      'Calories': 'Main_Dish_Calories'}, inplace = True)
sandwich_drink_salad.drop(['key'], axis = 1)

,Category_x,Item_x,Beverage_Calories,Category_y,Item_y,Salad_Calories,Category,Item,Main_Dish_Calories,Total Calories
0,Beverages,Coca-Cola Classic (Small),140,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Big Mac,530,810
1,Beverages,Coca-Cola Classic (Small),140,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Cheese,520,800
2,Beverages,Coca-Cola Classic (Small),140,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon & Cheese,600,880
3,Beverages,Coca-Cola Classic (Small),140,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,610,890
4,Beverages,Coca-Cola Classic (Small),140,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder Deluxe,540,820
...,...,...,...,...,...,...,...,...,...,...
6799,Beverages,Dasani Water Bottle,0,Salads,Premium Southwest Salad with Grilled Chicken,290,Chicken & Fish,Chicken McNuggets (6 piece),280,570
6800,Beverages,Dasani Water Bottle,0,Salads,Premium Southwest Salad with Grilled Chicken,290,Chicken & Fish,Chicken McNuggets (10 piece),470,760
6801,Beverages,Dasani Water Bottle,0,Salads,Premium Southwest Salad with Grilled Chicken,290,Chicken & Fish,Chicken McNuggets (20 piece),940,1230
6802,Beverages,Dasani Water Bottle,0,Salads,Premium Southwest Salad with Grilled Chicken,290,Chicken & Fish,Chicken McNuggets (40 piece),1880,2170
6803,Beverages,Dasani Water Bottle,0,Salads,Premium Southwest Salad with Grilled Chicken,290,Chicken & Fish,Filet-O-Fish,390,680

In [118]:
# Create a new column that is the sum of calories for each row
sandwich_drink_salad['Total Calories'] = sandwich_drink_salad['Beverage_Calories'] + sandwich_drink_salad['Salad_Calories'] + sandwich_drink_salad['Main_Dish_Calories']

In [99]:
sandwich_drink_salad.head()

,Category_x,Item_x,Beverage_Calories,key,Category_y,Item_y,Salad_Calories,Category,Item,Main_Dish_Calories,Total Calories
0,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Big Mac,530,810
1,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Cheese,520,800
2,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon & Cheese,600,880
3,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,610,890
4,Beverages,Coca-Cola Classic (Small),140,1,Salads,Premium Bacon Ranch Salad (without Chicken),140,Beef & Pork,Quarter Pounder Deluxe,540,820

In [95]:
# Print the average calorie count for a value meal
# Note: This does not count fries yet.
print(f'The average caloric count in a value meal is:', sandwich_drink_salad['Total Calories'].mean().round())

The average caloric count in a value meal is: 916.0

In [101]:
drinks_sandwiches =merge(drinks, sandwiches, on='key')

In [106]:
Snacks_and_sides = menu_calories[menu_calories['Category'] == 'Snacks & Sides'].copy()
Snacks_and_sides

           Category                                        Item  Calories
90   Snacks & Sides    Chipotle BBQ Snack Wrap (Crispy Chicken)       340
91   Snacks & Sides   Chipotle BBQ Snack Wrap (Grilled Chicken)       260
92   Snacks & Sides   Honey Mustard Snack Wrap (Crispy Chicken)       330
93   Snacks & Sides  Honey Mustard Snack Wrap (Grilled Chicken)       250
94   Snacks & Sides           Ranch Snack Wrap (Crispy Chicken)       360
95   Snacks & Sides          Ranch Snack Wrap (Grilled Chicken)       280
96   Snacks & Sides                          Small French Fries       230
97   Snacks & Sides                         Medium French Fries       340
98   Snacks & Sides                          Large French Fries       510
99   Snacks & Sides                           Kids French Fries       110
100  Snacks & Sides                                  Side Salad        20
101  Snacks & Sides                                Apple Slices        15
102  Snacks & Sides                     Fruit 'n Yogurt Parfait       150

In [107]:
med_french_fries = menu_calories[menu_calories['Item'] == 'Medium French Fries'].copy()

In [116]:
med_french_fries['key'] = 1
fries_drinks_sandwiches = merge(drinks_sandwiches, med_french_fries, on='key')

In [117]:
fries_drinks_sandwiches

,Category_x,Item_x,Calories_x,key,Category_y,Item_y,Calories_y,Category,Item,Calories
0,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Big Mac,530,Snacks & Sides,Medium French Fries,340
1,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Cheese,520,Snacks & Sides,Medium French Fries,340
2,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Bacon & Cheese,600,Snacks & Sides,Medium French Fries,340
3,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,610,Snacks & Sides,Medium French Fries,340
4,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder Deluxe,540,Snacks & Sides,Medium French Fries,340
...,...,...,...,...,...,...,...,...,...,...
1129,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (6 piece),280,Snacks & Sides,Medium French Fries,340
1130,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (10 piece),470,Snacks & Sides,Medium French Fries,340
1131,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (20 piece),940,Snacks & Sides,Medium French Fries,340
1132,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (40 piece),1880,Snacks & Sides,Medium French Fries,340
1133,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Filet-O-Fish,390,Snacks & Sides,Medium French Fries,340

In [119]:
fries_drinks_sandwiches.rename(columns = {'Calories_x':'Beverage_Calories',
                                      'Calories_y': 'Sandwich_Calories',
                                      'Calories': 'French_Fries_Calories'}, inplace = True)
fries_drinks_sandwiches['Total Calories'] = fries_drinks_sandwiches['Beverage_Calories'] + fries_drinks_sandwiches['Sandwich_Calories'] + fries_drinks_sandwiches['French_Fries_Calories']

In [120]:
fries_drinks_sandwiches

,Category_x,Item_x,Beverage_Calories,key,Category_y,Item_y,Sandwich_Calories,Category,Item,French_Fries_Calories,Total Calories
0,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Big Mac,530,Snacks & Sides,Medium French Fries,340,1010
1,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Cheese,520,Snacks & Sides,Medium French Fries,340,1000
2,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Bacon & Cheese,600,Snacks & Sides,Medium French Fries,340,1080
3,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,610,Snacks & Sides,Medium French Fries,340,1090
4,Beverages,Coca-Cola Classic (Small),140,1,Beef & Pork,Quarter Pounder Deluxe,540,Snacks & Sides,Medium French Fries,340,1020
...,...,...,...,...,...,...,...,...,...,...,...
1129,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (6 piece),280,Snacks & Sides,Medium French Fries,340,620
1130,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (10 piece),470,Snacks & Sides,Medium French Fries,340,810
1131,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (20 piece),940,Snacks & Sides,Medium French Fries,340,1280
1132,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Chicken McNuggets (40 piece),1880,Snacks & Sides,Medium French Fries,340,2220
1133,Beverages,Dasani Water Bottle,0,1,Chicken & Fish,Filet-O-Fish,390,Snacks & Sides,Medium French Fries,340,730

In [121]:
all_value_menu_options_calories = sandwich_drink_salad['Total Calories'].sum() + fries_drinks_sandwiches['Total Calories'].sum()

In [123]:
all_value_menu_options_average = all_value_menu_options_calories / (len(sandwich_drink_salad) + len(fries_drinks_sandwiches))

In [128]:
print(f'The average caloric value of the McDonalds value menu is: {all_value_menu_options_average.round()}.')

The average caloric value of the McDonalds value menu is: 926.0.